### ISSUE TITLE
Restore gives 502 Bad Gateway -- running nginx 1.8.0 to proxy to meteor, on Ubuntu 14.04

### ISSUE THREAD

**Issue by chrisco23** [hitchcott/app-dump#8]
So far I can't get the Restore to work.  My database is quite small, ~ 300K.  After some time, I get a 502 Bad Gateway reported in the nginx logs.  Any ideas?

**Comment by IstoraMandiri** [comment]
Sorry for the late response! I'm doing a round of updates on this package.

Could you provide anything from the nodejs logs? 

I've used this over NGINX before and it shouldn't have any problems. It could be that this package needs to be published for the linux arch, which in case it'll be fixed by #6

**Comment by IstoraMandiri** [comment]
I've published 0.2 for linux 32 an 64 bit. Please reopen if you have any problems.
